# Generated by Django 5.2.8 on 2025-11-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('kitchen_id', models.IntegerField()),
                ('date', models.DateField()),
                ('value_units_per_hour', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('hotel_id', 'kitchen_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('kitchen_id', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mid_hid', models.IntegerField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('smoke', models.FloatField(blank=True, null=True)),
                ('damper_pos', models.FloatField(blank=True, null=True)),
                ('exhaust_speed', models.FloatField(blank=True, null=True)),
                ('mains_voltage', models.FloatField(blank=True, null=True)),
                ('energy_cum', models.FloatField(blank=True, null=True)),
                ('log_id', models.IntegerField(blank=True, null=True)),
                ('reserve1', models.IntegerField(blank=True, null=True)),
                ('reserve2', models.IntegerField(blank=True, null=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['datetime_end'],
                'indexes': [models.Index(fields=['mid_hid', 'date', 'datetime_end'], name='dckv_device_mid_hid_dc99e0_idx')],
            },
        ),
    ]
