# Generated by Django 5.2.8 on 2025-12-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dckv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicereading',
            name='reserve1',
        ),
        migrations.RemoveField(
            model_name='devicereading',
            name='reserve2',
        ),
        migrations.AddField(
            model_name='devicereading',
            name='energy_interval',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='interval_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
